name: Tests

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - develop
    paths-ignore:
      - '**.md'

jobs:
  build-core:
    name: Build and Test semgrep-core
    runs-on: ubuntu-latest
    container: returntocorp/ocaml:alpine
    steps:
      - name: Pre-checkout fixes
        run: |
          sudo chmod -R 777 /github
          github_cache_dir="/__w"
          sudo mkdir -p "$github_cache_dir"
          sudo chmod -R 777 "$github_cache_dir"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Post-checkout fixes
        run: ./.github/post-checkout
      - name: Build semgrep-core and spacegrep
        run: ./scripts/install-alpine-semgrep-core
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ocaml-build-artifacts
          path: ocaml-build-artifacts.tgz
      - name: Test spacegrep
        run: opam exec -- make -C spacegrep test
      - name: Test semgrep-core
        run: |
          eval $(opam env)
          cd semgrep-core
          START=`date +%s`
          make test
          make e2etest
          END=`date +%s`
          TEST_RUN_TIME=$((END-START))
          curl --fail -L -X POST "https://dashboard.semgrep.dev/api/metric/semgrep.core.test-run-time-seconds.num" -d "$TEST_RUN_TIME"
      - name: Report Number of Tests Stats
        if: github.ref == 'refs/heads/develop'
        run: |
          ./semgrep-core/tests/report_test_metrics.sh

      # TODO: move this to a stable host for more reliable results.
      #
      # It's not clear how to push the stats only when "on the main
      # branch". The GitHub Actions documentation is unhelpful. So we
      # keep things simple and publish the results every time.
      #
      - name: Publish match performance
        run: |
          # This runs a short test suite to track the match performance
          # of semgrep-core over time. The results are pushed to the
          # dashboard at https://dashboard.semgrep.dev/
          #
          opam exec -- make -C semgrep-core report-perf

  tox-tests:
    name: semgrep tests with different python envs
    runs-on: ubuntu-latest
    needs: [build-core]
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: ocaml-build-artifacts
      - name: Install artifacts
        run: |
          tar xf ocaml-build-artifacts/ocaml-build-artifacts.tgz
          ls -lR ocaml-build-artifacts
          sudo cp ocaml-build-artifacts/bin/* /usr/bin
      - name: Test semgrep-core
        run: semgrep-core -version
      - name: Install Tox and any other packages
        run: pip install pipenv==2018.11.26 wheel==0.34.2 tox==3.15.0
      - name: Run Tox
        run: |
          cd semgrep
          tox -e py  # Run tox using the version of Python in `PATH`


  build-test:
    name: semgrep unit and e2e tests
    runs-on: ubuntu-latest
    needs: [build-core]
    strategy:
      matrix:
        python: [3.7]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: ocaml-build-artifacts
      - name: Install artifacts
        run: |
          tar xf ocaml-build-artifacts/ocaml-build-artifacts.tgz
          sudo cp ocaml-build-artifacts/bin/* /usr/bin
      - name: Install semgrep
        run: |
          cd semgrep
          export PATH=/github/home/.local/bin:$PATH
          pip3 install pipenv
          pipenv install --dev
      - uses: actions/cache@v2
        with:
          path: ~/.cache/semgrep-cache
          key: semgrep-repo-cache-test
      - name: create cache dir if not exists
        run: mkdir -p ~/.cache/semgrep-cache
      - run: touch ~/.cache/semgrep-cache/ok
      - name: Test semgrep
        run: |
          cd semgrep
          export PATH=/github/home/.local/bin:$PATH
          make ci-test
        env:
          GITHUB_REPO_CACHE: ~/.cache/semgrep-cache
      - name: Generate test matrix data
        run: |
          cd semgrep
          pipenv run ../scripts/generate_test_matrix.py --json --directory ../semgrep-core/tests/ --output-file test-matrix.json
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: test-matrix
          path: semgrep/test-matrix.json

  perf-test:
    name: semgrep perf tests
    runs-on: ubuntu-latest
    needs: [build-core]
    strategy:
      matrix:
        python: [3.7]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Run 0.17.0 Timing Benchmark
        run: |
          pip3 install semgrep==0.29.0
          semgrep --version
          semgrep-core -version
          python3 -m semgrep --version
          export PATH=/github/home/.local/bin:$PATH

          python3 scripts/calculate_ci_perf.py > semgrep/baseline_timing.txt
          cat semgrep/baseline_timing.txt
          pip3 uninstall -y semgrep
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: ocaml-build-artifacts
      - name: Install artifacts
        run: |
          tar xf ocaml-build-artifacts/ocaml-build-artifacts.tgz
          sudo cp ocaml-build-artifacts/bin/* /usr/bin
      - name: Install semgrep
        run: |
          cd semgrep
          pip3 install pipenv
          pipenv install --dev
      - name: Get timing for latest semgrep
        run: |
          cd semgrep
          pipenv run semgrep --version
          pipenv run python -m semgrep --version
          pipenv run semgrep-core -version
          pipenv run python3 ../scripts/calculate_ci_perf.py > timing.txt
          cat timing.txt
      - name: Compare timing infos
        run: |
          python scripts/compare_perf.py semgrep/baseline_timing.txt semgrep/timing.txt
